  effort_controller: 
    type: effort_controllers/JointTrajectoryController
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    gains:
      j1:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j2:
        p: 1000
        d: 10
        i: 1
        i_clamp: 1
      j3:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j4:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j5:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j6:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
  velocity_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    gains:
      j1:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j2:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j3:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j4:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j5:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j6:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
  position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    gains:
      j1:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j2:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j3:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j4:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j5:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
      j6:
        p: 1000
        d: 1
        i: 1
        i_clamp: 1
